### ISSUE TITLE
Conditional sentence from meg.json

### ISSUE THREAD

**Issue by guiomar** [atapscott/Armitage_BIDS_NLG#5]
"Recording_properties": 
if {RecordingType}=="continuous": "The experiment was recorded continuously during {RecordingDuration} seconds.", 
if {RecordingType}=="epoched":  "The experiment was recorded during {RecordingDuration} seconds, epoched in segments of {EpochLength} seconds.",

**Comment by atapscott** [comment]
Lo dejé así, creo que viene a ser la lógica que indicas

```
{% if RecordingType == 'continuous' %}The experiment was recorded continuously during {{RecordingDuration}} seconds.{% elif RecordingType == 'epoched' %}The experiment was recorded during {{RecordingDuration}} seconds, epoched in segments of {{EpochLength}} seconds.{% endif %}
```

Un ejemplo de render (de OMEGA, no encuentro epoch por ahora):

```
The experiment was recorded continuously during 600 seconds.

```

**Comment by guiomar** [comment]
Así está genial!

Muchas gracias @atapscott !!
